227-238 Verification register-page into Main
Zensurversuch/Kantinerado pull request #107
Opened 2024-08-27 05:14 UTC by Schmidt-N

2024-09-02 08:32 UTC, Schmidt-N commented on Web-App/Frontend/Dockerfile
> +ARG ANGULAR_ENVIRONMENT=development
Varaible der .env einfügen

2024-09-05 22:38 UTC, kirchert requested changes

2024-09-05 22:38 UTC, kirchert commented on Web-App/Frontend/src/app/components/register/register.component.html
> +      <input id="password" formControlName="password" type="password" class="register__input" [minlength]="8" [maxlength]="50">
Buchstaben wie ä,ö,ü und ß werden im Passwort Feld nicht akzeptiert.
Falls das so gewollt ist, müsste die Fehlermeldung geändert werden

2024-09-05 22:39 UTC, kirchert commented
eine README zum Ausführen der Tests wäre noch gut.

2024-09-06 05:44 UTC, Schmidt-N commented on Web-App/Frontend/src/app/components/register/register.component.html
> +      <input id="password" formControlName="password" type="password" class="register__input" [minlength]="8" [maxlength]="50">
Umlaute gibt es nicht i allen Sprachen, somit sollte das gewollt sein.

2024-09-06 14:34 UTC, kirchert approved these changes

2024-09-06 14:34 UTC, merged