32 gerichtvorschläge into main
Zensurversuch/Kantinerado pull request #110
Opened 2024-09-02 08:39 UTC by kirchert

Bitte Niklas seine pull requests zuerst mergen

2024-09-03 16:09 UTC, michi3001 commented on Web-App/Backend/__init__.py
> +    POSTGRES_URL = app.config['SQLALCHEMY_DATABASE_URI']
SQLALCHEMY_DATABASE_URI ist der falsche Name. SQLAlchemy ist nur das ORM Framework nene es um zu POSTGRES_DATABASE__URI oder so und schreibe immer einen Eintrag in der README sodass der Rest weiß das diese Variable gesetzt werden muss

2024-09-03 16:10 UTC, michi3001 reviewed
Schreibe irgendwo auf wie man die Tests ausführt. In der Readme oder wie auch immer

2024-09-03 18:22 UTC, michi3001 requested changes

2024-09-03 18:22 UTC, michi3001 commented on Web-App/docker-compose.test.yml
> +services:
Irgendwo beschreiben wieso das File genutzt wird oder wie man es nutzt. Das muss vor den Tests ja manuell gestartet werden (docker compose -f .\docker-compose.test.yml up --build)? Oder gibts da nen anderen weg oder passiert das automatisch?

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/tests/unit/conftest.py
> +        engine = create_engine(app.config['SQLALCHEMY_DATABASE_URI'])
Hier auch wieder die eigentlich falsch benannte Variable

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/initialize_database.py
> +#test Datenbank
Kommentar auf englisch

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +def test_create_dish_suggestion_succes_admin(client, auth_token_admin, session, delete_all_dish_suggestions):
success mit 2s

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +    """Test creating a dish suggestionas admin."""
fehlendes Leerzeichen

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +    assert response_acceptSuggestion.json[API_MESSAGE_DESCRIPTOR] == f"{get_api_messages.WARNING.value}Gericht erfolgreich erstellt, aber die folgenden Allerigie ['TestAllergyThree'] sind nicht in de
Wofür der Parameter delete_all_dish_suggestions

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/__init__.py
> +    # Konfiguration laden
Kommentare Englisch

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/app.py
> +app = create_app(config_name=os.getenv('FLASK_CONFIG', 'ProductionConfig'))
Hier auch in der README beschreiben (wenn .env variable) was diese Variable ist und was man setzen muss

2024-09-03 18:22 UTC, michi3001 commented on Web-App/Backend/app.py
> +app = create_app(config_name=os.getenv('FLASK_CONFIG', 'ProductionConfig'))
Und wird hier dann die config von config.py genommen oder wie läuft das

2024-09-03 18:31 UTC, Schmidt-N commented on Web-App/Backend/DB_Repositories/models.py
> +    description = Column(String(150))
Für die BEschreibung des Gerichts, die wollte ich dann nch bei den normalen Gerichten einfügen.

2024-09-04 07:30 UTC, Schmidt-N commented on Web-App/Backend/config.py
> +    """Basis-Konfigurationsklasse."""
Kommentare wieder auf Englisch, merhfach in dieser Datei.

2024-09-04 07:30 UTC, Schmidt-N commented on Web-App/Backend/routes_blueprints/dishSuggestion_routes.py
> +def accept_dish_suggestion():
Hier sollten wir noch schauen wie wir es machen. 
Im Frontend gibt es leider kein Interface mit Variablen beider Seiten (DishSuggestion und Dish), deswegen hätte ich das ganze in zwei Unterschiedliche API-Anfragen gekoppelt und nicht alles auf einmal gemacht. Dahingehend würde ich gerne ne Diskussion mit euch anstoßen.

2024-09-04 07:30 UTC, Schmidt-N commented on Web-App/docker-compose.test.yml
> +services:
Nein, soweit ich weiß gibts keinen anderen weg. sollten wir dann in der READ.ME ergänzen.

2024-09-04 10:39 UTC, kirchert commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +    assert response_acceptSuggestion.json[API_MESSAGE_DESCRIPTOR] == f"{get_api_messages.WARNING.value}Gericht erfolgreich erstellt, aber die folgenden Allerigie ['TestAllergyThree'] sind nicht in de
damit vor dem Test alle vorhandenen dish_suggestion gelöscht werden

2024-09-04 13:00 UTC, kirchert commented on Web-App/Backend/app.py
> +app = create_app(config_name=os.getenv('FLASK_CONFIG', 'ProductionConfig'))
die FLASK_CONFIG wird in der docker-compose festgelegt und entscheidet, welche Konfiguration aus der config.py angewandt wird, so ist es möglich, dass z.B. eine andere URL für die Testdatenbank verwendet wird, wie für die Produktionsdatenbank

2024-09-04 13:07 UTC, kirchert commented on Web-App/Backend/routes_blueprints/dishSuggestion_routes.py
> +def accept_dish_suggestion():
{
    "dishSuggestionID": 123,
    "dishData": {
        "name": "Vegan Burger",
        "price": 9.99,
        "ingredients": ["Bun", "Lettuce", "Tomato", "Vegan Patty", "Pickles"],
        "dietaryCategory": "Vegan",
        "mealType": "Main Course",
        "image": "https://example.com/images/vegan-burger.jpg",
        "allergies": ["Gluten", "Soy"]
    }
}

somit könntest du innerhalb der dishData dein Interface anwenden und muss nur die dishSuggestionID hinzufügen

2024-09-04 13:42 UTC, kirchert commented on Web-App/Backend/__init__.py
> +    POSTGRES_URL = app.config['SQLALCHEMY_DATABASE_URI']
Hab es umbenannt, jedoch muss diese Variable nicht gesetzt werden, sie wird in der config.py festgelegt. Ein Eintrag in der README ist also nicht nötig?

2024-09-04 13:56 UTC, kirchert commented on Web-App/Backend/routes_blueprints/allergy_routes.py
> +from flask import Blueprint, jsonify, current_app
wird benötigt, damit das mit dem neuem Aufbau des Backends und den Tests funktioniert

2024-09-04 13:57 UTC, kirchert commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +    """Test creating a dish suggestionas admin."""
wo genau?

2024-09-04 19:21 UTC, michi3001 commented on Web-App/Backend/tests/unit/test_dish_suggestion.py
> +    """Test creating a dish suggestionas admin."""
suggestion as

2024-09-04 19:22 UTC, michi3001 approved these changes

2024-09-06 14:35 UTC, merged