216-264-Password-salt
Zensurversuch/Kantinerado pull request #111
Opened 2024-09-03 14:25 UTC by Zensurversuch

2024-09-03 16:16 UTC, michi3001 approved these changes

2024-09-04 11:05 UTC, Schmidt-N requested changes

2024-09-04 11:05 UTC, Schmidt-N commented on Web-App/Backend/DB_Repositories/userRepository.py
> +                    "salt": user_data.salt,
Des salt sollte glaub ich ähnlich wie das Passwort bahndelt werden und somit,wenn möglich, nicht in das Frontend gelangen.

2024-09-06 14:38 UTC, Schmidt-N commented on Web-App/Backend/DB_Repositories/userRepository.py
> +                    "salt": user_data.salt,
Sorry, passt ich war bei den routes.

2024-09-06 15:05 UTC, kirchert requested changes
Konnte mich nicht mehr einloggen und auch keinen neuen Benutzer erstellen

2024-09-06 15:05 UTC, kirchert commented on Web-App/Backend/DB_Repositories/userRepository.py
> +                    "salt": user_data.salt,
glaube schon das bei der route user_by_email der Salt und das Passwort zurückgegeben werden

2024-09-07 12:51 UTC, Schmidt-N approved these changes

2024-09-09 08:17 UTC, kirchert approved these changes

2024-09-09 08:27 UTC, merged